### ISSUE TITLE
[bug] No Close on popup window

### ISSUE THREAD

**Issue by andyredfern** [hkgnp/logseq-calview-plugin#1]
It could be me, but when I press the calendar pop up there is no way to close the pop up window down. Running on Windows 10 logseq version 0.5.9

**Comment by benjypng** [comment]
You can press Escape or update to 1.3.2 and you can click anywhere outside
the windows to close it.

**Comment by andyredfern** [comment]
Perfect 1.3.2 fixes issue! thank you
