### ISSUE TITLE
icon can not load in header

### ISSUE THREAD

**Issue by XinLi0111** [hkgnp/logseq-calview-plugin#2]
Thanks for your brilliant plugin!

I meet a problem when I installed the plugin, the icon was not showed in the header bar, and it appears after I reload several times, but the time doesn't parse, nothing found in the plugin window, and the icon disappeared after I reload again.

I use windows 11 and logseq APP 0.6.1.
![image](https://user-images.githubusercontent.com/31495943/155334358-79c81481-7faf-43e2-9ecb-4f6206ae6ce3.png)

**Comment by XinLi0111** [comment]
might the internet problem, I see an error of loading the icon from a website

**Comment by benjypng** [comment]
Hi, I cannot seem to reproduce this error. 

- Are there other plugins installed?
- How did you install this plugin?

**Comment by XinLi0111** [comment]
Yes, I installed some plugins. But the problem is still there after I close all the plugins.

I install it from the market.

![image](https://user-images.githubusercontent.com/31495943/155529683-dc8a8844-b883-47c6-8933-3a4e43565588.png)
![image](https://user-images.githubusercontent.com/31495943/155529971-b727159c-e704-4b01-b6d2-3bd697e17213.png)

**Comment by benjypng** [comment]
Hmm, I am not sure how or why this happened. I am still not able to reproduce it.
Could you try to re-install the plugin using the below steps?

1) Uninstall plugin
2) Close Logseq
3) Delete logseq-calview-plugin.json from .logseq/settings folder
4) Open Logseq
5) Re-install plugin
6) Restart Logseq

**Comment by XinLi0111** [comment]
it works, thanks a lot!😁
