### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by hodanli** [hkgnp/logseq-calview-plugin#3]
hi,

thanks for great plugin. this is so cool that i might stop using calendar altogether. 

for me it was working great but i guess after the last update it stopped. i deleted and reinstalled but could not solve the issue. this is what i get when i click the calendar icon:

![image](https://user-images.githubusercontent.com/6535865/155682396-f8bea59f-7bdd-4785-bbd6-6a2dd31ef5be.png)

**Comment by benjypng** [comment]
I have not made any significant changes to the plugin since I released it.

This could mean that there is some issue with the query. Are you able to open up the developer console or take a screenshot of the blocks that contain the appointment elements?

**Comment by hodanli** [comment]
![image](https://user-images.githubusercontent.com/6535865/155769165-d9006014-b9e4-423f-942f-8adffc361bcc.png)

**Comment by benjypng** [comment]
Could you try to: 
1) Delete the plugin
2) Close Logseq
3) Delete logseq-calview-plugin from .logseq/settings
4) Open Logseq
5) Install plugin
6) Restart Logseq

**Comment by hodanli** [comment]
it doesn't change anything unfortunately.

**Comment by benjypng** [comment]
Hmm, apologies then I am really not sure why this is the case. 
Will leave this issue open to see if anyone else faces the same issue.

**Comment by meldarionqeusse** [comment]
Hi, I am also facing the same issue nothing is showing up in the calendar. I tried deleting and reinstalling plugin and even starting fresh on another system

**Comment by benjypng** [comment]
What version of Logseq are you on?

**Comment by meldarionqeusse** [comment]
I am running Version 0.6.1

**Comment by benjypng** [comment]
Could you try 0.5.9 and see if the issue persists? v0.6.1 is giving me some issues with plugins as well.

**Comment by klzkbln** [comment]
same problem as @hodanli here unfortunately - calview plugin suddenly stopped working few days ago (logseq 0.6.5.)

**Comment by benjypng** [comment]
Hmm, it is still working for me in 0.6.7. Could you share more about what does stopped working mean?
Will be great if you could also include how your markdown looks like.
Thanks!

**Comment by klzkbln** [comment]
it might still work in the background, but i cannot use it: when i click the calview-icon, i get "today's appointments" but not the calendar beneath, when i then click the fullscreen-icon, it just expands horizontally, but not vertically.
 
<img width="975" alt="Bildschirmfoto 2022-05-16 um 11 55 41" src="https://user-images.githubusercontent.com/105369165/168568452-eba39bba-1808-41f3-9dd1-1968ed7207fb.png">
<img width="977" alt="Bildschirmfoto 2022-05-16 um 11 55 54" src="https://user-images.githubusercontent.com/105369165/168568457-4760937d-7a15-46bf-a407-ad6d35e383f8.png">

**Comment by benjypng** [comment]
Hmm, there may be an issue with the query.
Let me see if some refactoring can help.

**Comment by benjypng** [comment]
Do you mind trying v1.4.1 to see if there are still issues, please?

**Comment by nohjlau** [comment]
It was working fine a little bit ago, and then now the calendar loads, but it doesn't populate. The console is reporting this error at journalDayInNumber.toString(): 

```
utils.tsx:4 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
    at RD (utils.tsx:4)
    at ND (utils.tsx:89)
    at async App.tsx:21
```

**Comment by benjypng** [comment]
Could you share the block that you added?

**Comment by nohjlau** [comment]
Ok okay, my issue might be different from the one that people are reporting here. I'm not sure. My bug occurs when there's a task scheduled outside of a journal page. As soon as I deleted the task that is outside of the journal pages the calendar starts working again

@hodanli also has the toString issue, but his console reports additional errors, which I didn't have. As of now, I'm having no issues on Windows Logseq v0.6.9.

**Comment by benjypng** [comment]
> Ok okay, my issue might be different from the one that people are reporting here. I'm not sure. My bug occurs when there's a task scheduled outside of a journal page. As soon as I deleted the task that is outside of the journal pages the calendar starts working again
> 
> @hodanli also has the toString issue, but his console reports additional errors, which I didn't have. As of now, I'm having no issues on Windows Logseq v0.6.9.

Yeah, it only works with the items on a journal page as that is how the date is derived for the calendar. If it is on a regular page, then there is no date component. But I will look into the possibility of handling it so that it's more obvious.

I have done some refactoring which should resolve some of those other reports, but will leave this issue open just in case.

**Comment by klzkbln** [comment]
> Do you mind trying v1.4.1 to see if there are still issues, please?

just updated to v1.4.2 - now the calendar displays and expands correctly, but unfortunately all my appointments are gone and a new one i created just now won't show up in the calendar … recurrence and datenlp plugins are enabled and up to date.

**Comment by benjypng** [comment]
> > Do you mind trying v1.4.1 to see if there are still issues, please?
> 
> just updated to v1.4.2 - now the calendar displays and expands correctly, but unfortunately all my appointments are gone and a new one i created just now won't show up in the calendar … recurrence and datenlp plugins are enabled and up to date.

Could you share a screenshot of the events that you have created, including the title of the page that the event is on, please?

**Comment by klzkbln** [comment]
<img width="845" alt="Bildschirmfoto 2022-05-23 um 08 55 35" src="https://user-images.githubusercontent.com/105369165/169761195-d5a15b1d-a1c6-4967-8ac9-f299f111ed87.png">

**Comment by nohjlau** [comment]
> just updated to v1.4.2 - now the calendar displays and expands correctly, but unfortunately all my appointments are gone and a new one i created just now won't show up in the calendar … recurrence and datenlp plugins are enabled and up to date.

@klzkbln Now your issue sounds more in line with the issue I had.  Press `Ctrl + Shift + I` on your current graph and see if you get the `ToString `error. Also, make a new graph and try to create an appointment on the journal entry. If the appointment shows up, then chances are your current has schedules that aren't on a journal page and the plugin gets a null error. As long as you have 1 appointment outside of the journal your entire calendar won't display.

**Comment by benjypng** [comment]
Could you all try v1.4.4 and see if it works?
I've added in a check so incorrect events do not prevent the correct events from showing.

**Comment by klzkbln** [comment]
@nohjlau `Ctrl + Shift + I` doesn't do anything for me (am on macOs and german keyboard), but i created an appointment in a new/empty graph as you proposed and voilà – appointment shows up in calendar!

@hkgnp v1.4.3 fixed the issue for me (despite maybe still having appointments in places they don't belong), all my appointments are visible again. thank you!

**Comment by benjypng** [comment]
Happy to hear that! Thanks all for reporting the bug and being so patient!

**Comment by nohjlau** [comment]
1.4.3+ introduces a quirky kind of bug that prevents appointments from displaying. This isn't found in 1.4.2. It took me a bit to reproduce. What happens is if you create a page reference to itself then the appointments won't display even if you delete the reference and re-index. I'm completely baffled as to why re-indexing doesn't fix it. To reproduce it, simply create a self-referencing link, so in page "2022-05-23" if I create a reference "[[2022-05-23]]" appointments are no longer displayed. I've included images for reference

![image](https://user-images.githubusercontent.com/52471958/169955477-98eb0060-0529-47ba-a20f-3e98eaa0dabd.png)

**Comment by benjypng** [comment]
Hi, I am not able to replicate this issue though. Can you try to update to v1.4.5 and see if the issue still happens?
I am currently on v1.4.5 and on the latest nightly.

**Comment by nohjlau** [comment]
Yeah, the bug still occurs in v1.4.5. You might have to re-index your graph first for the appointments to disappear. This can also occur if you change the date format in the settings.

**Comment by benjypng** [comment]
Haha, those are not things that I usually do and a little hesitant to do for my graph right now.

In my experience, changing the date formats causes all sorts of issues for various plugins actually, not just calview. 

Can I confirm that if you do not reindex, or change the date format, this issue is not present?

**Comment by nohjlau** [comment]
Yes, if you don't re-index the appointments still display. The thing that has me scratching my head is once you delete the self-reference re-indexing doesn't fix the problem. I created a video reproducing the issue. There's no errors in the console either..

https://user-images.githubusercontent.com/52471958/169960465-ec4a250a-c032-4947-b4ed-b4f99f7951fd.mp4

.

**Comment by benjypng** [comment]
Could you try v1.4.6 please?
It seems that after a re-index, some block properties actually get changed/ removed. Hence, needed to use another way to check for journal blocks.

**Comment by nohjlau** [comment]
It's working great. Thanks for taking the time to look into the issues and the quick responses
