### ISSUE TITLE
Feature Request: Ability to add all-day tasks

### ISSUE THREAD

**Issue by r-hegde** [hkgnp/logseq-calview-plugin#4]
It would be great if tasks scheduled for the day with no start and end time are shown as all-day tasks on the top of the calendar

**Comment by benjypng** [comment]
Hi, this is available in the latest update. You can either use the datenlp-plugin to create an all day event with @allday or do it like this:

```
Reply to Jane
start-time:: all-day
```

**Comment by r-hegde** [comment]
Works great, thanks!
