### ISSUE TITLE
Feature suggestion: Remove TODO prefix and MD formatting

### ISSUE THREAD

**Issue by r-hegde** [hkgnp/logseq-calview-plugin#5]
This is a 2-part suggestion. (I'm not sure how difficult it is to implement this, so feel free to ignore the suggestion :)).

1. Remove the prefix TODO/DONE etc. in the calview
2. It is quite distracting to see the "raw" markdown text in the calview.
    For example, if we have something like:
   - [ ] TODO complete reading this [thing]\(link-of-the-thing)

    The entire block is displayed as raw content in the calendar. Ideally, we would see the above task in the calview as:

     complete reading this [thing](https://www.merriam-webster.com/dictionary/thing)

Bonus suggestion:

- Grey-out DONE tasks

**Comment by benjypng** [comment]
Hi! 

Have you tried the other calendar plugin? It is much more fully featured as I think it was meant to be something more holistic: https://github.com/haydenull/logseq-plugin-agenda

May meet your needs better!

**Comment by r-hegde** [comment]
I'll give that a try, thanks!
