### ISSUE TITLE
Customize width % based on view mode

### ISSUE THREAD

**Issue by nohjlau** [hkgnp/logseq-calview-plugin#6]
I'd like to be able to customize the view % based on the view. I tend to use the Logseq maximized and sometimes when I am in the middle of something I want to take a quick glance at my calendar without messing with my workflow. I've attached an example of how it would look at the bottom. I just changed the width % in the CSS and it works fine for Day view, but gets scrunched up for Month view.

I'm thinking that inside the settings file alongside `startDayHour` and `endDayHour` there can be additional an variable for `Day Width %`  which will determine how much of the screen is taken over by the calendar.

We can get the current view through `ViewState` using the properties `currentViewName` and `onCurrentViewNameChange`. I believe these can be added in Calendar.tsx. Here is the documentation for [ViewState](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/view-state/). These values would then be read inside of App.tsx and either `toggleFullScreen` would be modified or a new function added. I'm okay using the hacky CSS method, but other people might enjoy the customization so I thought I'd bring it up. Let me know your thoughts. Thanks!

![image](https://user-images.githubusercontent.com/52471958/169832801-b36974e4-3d3a-4826-ac88-6de8c79c4dd7.png)

**Comment by benjypng** [comment]
Hi thanks for the suggestion. I have added an option to change the width on the fly, and have it saved to the settings.
If you would like to add the hooks, will definitely welcome a PR!

**Comment by nohjlau** [comment]
Adjusting the window works great. However, it appears that full screen no longer works.

**Comment by benjypng** [comment]
Apologies this has been fixed in v1.4.8.

**Comment by nohjlau** [comment]
It work! Thanks for the quick response and all the coding you've been doing. This plugin is top notch! It's lightweight and sticks to the ethos of Logseq. I expect more and more people to start using it. :)
