### ISSUE TITLE
Appointment not shown in calendar

### ISSUE THREAD

**Issue by mwl72** [hkgnp/logseq-calview-plugin#8]
I installed your plugin. 
I tried an appointment. However it is not shown in the calendar (screenshot
<img width="1200" alt="Bildschirmfoto 2022-09-17 um 16 39 28" src="https://user-images.githubusercontent.com/68160608/190862660-18d9c4c1-b99a-4348-b490-dbb073614384.png">

is it possible to change the start of the week to Monday?

**Comment by KyleMondron** [comment]
I also am experiencing this issue. I have exited and re-entered the app to no avail. I also tried to delete and event, and then re-create it, but this failed. 

I am using the amazing plugin you designed for setting recurrence as well, so I deleted and re-created the recurrence, but this did not work either. I'm happy to submit any details you might want for debugging. Thank you for help in resolving this, these plugins have great functionality and utility for organizing my daily tasks.

**Comment by klzkbln** [comment]
exact same issue as above …

**Comment by benjypng** [comment]
Please try v1.4.10 and let me know if it's fixed.

**Comment by benjypng** [comment]
Change of start day of week view is also available now in v1.5.0.
