### ISSUE TITLE
Events shorter than 30 minutes are displayed as [object Object]

### ISSUE THREAD

**Issue by weaselshit** [hkgnp/logseq-calview-plugin#9]
Hi! Please, see attached screenshot. 

I have noticed that some of my events are not displayed properly, and click to block doesn't work on them.

I was able to narrow it down to the lenght of the event. Anything shorter than 30 minutes appears broken. Unfortunately, I wasn't able to track down the relevant code. Is that somehow intentional? Are you aware of a possible workaround?

![20230918_17h04m50s_grim](https://github.com/hkgnp/logseq-calview-plugin/assets/98793/9aba7c13-1b33-4812-8632-29d212a3f6a7)

**Comment by benjypng** [comment]
Please try v2.0.0.

**Comment by weaselshit** [comment]
Hi! 

2.0.0 doesn't work for me at all, nothing happens anymore when the button is pressed.

Here is the an example of an error from a developer console:
```
Uncaught (in promise) Error: No page found
    at dA (index-a40ab97e.js:102:168)
    at async Object.show (index-a40ab97e.js:102:905)
dA	@	index-a40ab97e.js:102
await in dA (async)		
(anonymous)	@	index-a40ab97e.js:28
```

Here is (as far as I understand) relevant code:
```
        const o = await logseq.Editor.getPage(i[0].page.id);
        if (!o || !o.journalDay)
            throw new Error("No page found");
```

I definitely have a journal page open.

Not sure if it's relevant, but my `:journal/page-title-format` is `yyyy-MM-dd EEEE`

Same behaviour on logseq-0.9.17 (which I had at the moment of opening this issue) and logseq-0.9.18. Both with and without logseq-datenlp-plugin (I noticed it was also recently updated so I tried to elimitate that variable).

**Comment by benjypng** [comment]
Hmm, I have that date format set and I can't reproduce the issue. 

Could you try to uninstall the plugin, close Logseq, from the plugin files from `.logseq/settings`, open Logseq and re-install the plugin?

**Comment by weaselshit** [comment]
Hi! Thank you for asking me to double-check things. I did clean up `.logseq/settings`, but wasn't aware of `.config/Logseq`. Ended up trying a new version of the plugin in a clean room environment. Works fine, and looks nicer, too. Thanks!

If you don't mind, I'd like to keep this issue open for now. I suspect some interferrence from some other plugin (like a different version of the same lib used?), and I would like to try to track it down.

**Comment by weaselshit** [comment]
I think I found something. Looks like it breaks when there is at least one non-journal page in the graph that has at least one block with either `start-time` or `end-time` properties present (with or without value). Doesn't seem to be related to the original problem. I will create a new issue and close this one.
